/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvShowsSplatRouteImport } from './routes/tv-shows.$'
import { Route as MoviesSplatRouteImport } from './routes/movies.$'
import { Route as TypeSlugRouteImport } from './routes/$type.$slug'

const TvShowsSplatRoute = TvShowsSplatRouteImport.update({
  id: '/tv-shows/$',
  path: '/tv-shows/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSplatRoute = MoviesSplatRouteImport.update({
  id: '/movies/$',
  path: '/movies/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeSlugRoute = TypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$type/$slug': typeof TypeSlugRoute
  '/movies/$': typeof MoviesSplatRoute
  '/tv-shows/$': typeof TvShowsSplatRoute
}
export interface FileRoutesByTo {
  '/$type/$slug': typeof TypeSlugRoute
  '/movies/$': typeof MoviesSplatRoute
  '/tv-shows/$': typeof TvShowsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$type/$slug': typeof TypeSlugRoute
  '/movies/$': typeof MoviesSplatRoute
  '/tv-shows/$': typeof TvShowsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$type/$slug' | '/movies/$' | '/tv-shows/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/$type/$slug' | '/movies/$' | '/tv-shows/$'
  id: '__root__' | '/$type/$slug' | '/movies/$' | '/tv-shows/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TypeSlugRoute: typeof TypeSlugRoute
  MoviesSplatRoute: typeof MoviesSplatRoute
  TvShowsSplatRoute: typeof TvShowsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-shows/$': {
      id: '/tv-shows/$'
      path: '/tv-shows/$'
      fullPath: '/tv-shows/$'
      preLoaderRoute: typeof TvShowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$': {
      id: '/movies/$'
      path: '/movies/$'
      fullPath: '/movies/$'
      preLoaderRoute: typeof MoviesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/$slug': {
      id: '/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/$type/$slug'
      preLoaderRoute: typeof TypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TypeSlugRoute: TypeSlugRoute,
  MoviesSplatRoute: MoviesSplatRoute,
  TvShowsSplatRoute: TvShowsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
